# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install all dependencies (including devDependencies) for building
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --production --ignore-scripts

# Copy built files from builder
COPY --from=builder /app/build ./build

# Expose port if necessary (currently unused)
# EXPOSE 3000

# Start the server
CMD [ "node", "build/index.js" ]
